//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentId { get; set; }
        public Nullable<int> postId { get; set; }
        public Nullable<int> userId { get; set; }
        public string body { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
